version: '2.1'

networks:
  test:

services:

  db:
    container_name: labwork5_mysql
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: labwork5
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - test
  server:
    container_name: labwork5_server
    build: server
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '9000:9000'
    expose:
      - '9000'
    networks:
      - test
  client:
    container_name: labwork5_client
    build: client
    restart: always
    ports:
      - '3000:80'
    expose:
      - '3000'
    networks:
      - test
